// autoload.php @generated by Composer 

<? return ComposerAutoloaderInit_IhMToegs9WHGWRF8/UrzEd86I76cKLiLSpX5jHpUl7nA6MP29nal1Ato9qMoik9Ewgks1/w4d/U6sVkX+KkYIMCGrL37ED3k+emgn3CK8nWqZz8UHwGIQDNdq3ex+9nh::getLoader(); ?>